version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalog:
    image: eventadvisor/eventcatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlservereventadvisor;Initial Catalog=EventCatalogDb;User Id=sa;Password=EventApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      ExternalBaseUrl: http://localhost:7053
    ports:
      - "7053:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlservereventadvisor

  eventstokenserver:
    image: eventadvisor/tokenapi
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=tokenmssqlserver;Initial Catalog=EventsTokenServiceDb;User Id=sa;Password=EventApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      MvcClient: http://localhost:7070
    ports:
      - "7054:80"
    container_name: eventstokencontainer
    networks:
      - frontend
      - backend
    depends_on:
      - tokenmssqlserver

  eventwebmvc:
    image: eventadvisor/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventCatalogUrl: http://eventcatalog
      IdentityUrl: http://192.168.86.27:7054
      CallBackUrl: http://localhost:7070
    ports:
      - "7070:80"
    container_name: eventwebcontainer
    networks:
      - frontend
    depends_on:
      - eventcatalog
      - eventstokenserver

  mssqlservereventadvisor:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: EventApi123(!)
    ports:
      - "7005:1433"
    container_name: eventsqlserver
    networks:
      - backend

  tokenmssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: EventApi123(!)
      SA_PASSWORD: EventApi123(!)
    ports:
      - "7011:1433"
    container_name: eventstokensqlserver
    networks:
      - backend

      
