version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalog:
    image: eventadvisor/eventcatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlservereventadvisor;Initial Catalog=EventCatalogDb;User Id=sa;Password=EventApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      ExternalBaseUrl: http://localhost:7053
    ports:
      - "7053:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlservereventadvisor

  eventstokenserver:
    image: eventadvisor/tokenapi
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlservereventadvisor;Initial Catalog=EventsTokenServiceDb;User Id=sa;Password=EventApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      MvcClient: http://localhost:7070
    ports:
      - "7054:80"
    container_name: eventstokencontainer
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlservereventadvisor

  eventscart:
    image: eventadvisor/cartapi
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    environment:
      IdentityUrl: http://192.168.86.27:7054
      ConnectionString: eventbasket.data
    ports:
      - "7055:80"
    container_name: eventadvisorcartapi
    networks:
      - frontend
      - backend
    depends_on:
      - eventstokenserver
      - eventbasket.data
      
  eventsorder:
    image: eventadvisor/orderapi
    build: 
      context: .\OrderAPI
      dockerfile: Dockerfile
    environment:
      IdentityUrl: http://192.168.86.27:7054
      ConnectionString: "Data Source=eventadvisororderserver;Initial Catalog=OrdersDb;User Id=sa;Password=EventApi123(!);TrustServerCertificate=false;Encrypt=false;"
    ports:
      - "7018:1433"
    container_name: eventadvisororderapi
    networks:
      - frontend
      - backend
    depends_on:
      - eventadvisororderserver
      - eventstokenserver

  eventwebmvc:
    image: eventadvisor/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventCatalogUrl: http://eventcatalog
      IdentityUrl: http://192.168.86.27:7054
      CallBackUrl: http://localhost:7070
      CartUrl: http://eventscart
      OrderUrl: http://eventsorder
      StripePrivateKey: sk_test_51MVsoUJ4FlY8ZnAHiut2VteIn4aoqcz8LWIQMVFR19nKKkmz9RaVgGwtpw5kGYkZZJFl9QGlKrFcKTofiwopgM7m006obbGQXK
      StripePublicKey: pk_test_51MVsoUJ4FlY8ZnAH4cmP3aLo4AlqTx5TIHWeQlSaDqeAvvcZ1EEXJoVKSpXz8Do655Y6fKNvuBLvyme7WDwCLZDz00W1yoJxE2
    ports:
      - "7070:80"
    container_name: eventwebcontainer
    networks:
      - frontend
    depends_on:
      - eventcatalog
      - eventstokenserver
      - eventscart
      - eventsorder

  mssqlservereventadvisor:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: EventApi123(!)
    ports:
      - "7005:1433"
    container_name: eventsqlserver
    networks:
      - backend  

  eventbasket.data:
    image: redis
    ports:
      - "7012:6379"
    container_name: eventbasketdata
    networks:
      - backend

  eventadvisororderserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: EventApi123(!)
    ports:
      - "7013:1433"
    container_name: ordersqlserver
    networks:
      - backend
